// The package swagger provides capabilities for generating and displaying Swagger/OpenAPI documentation
// Based on swaggo/swag for documentation generation driven by comments
package swagger

import "time"

// Configure Swagger settings
type Config struct {
	// Enabled whether to enable Swagger (default false)
	Enabled bool `mapstructure:"enabled"`

	// UIPath Swagger UI route path (default "/swagger/*any")
	UIPath string `mapstructure:"ui_path"`

	// SpecPath OpenAPI Spec route path (default "/openapi.json")
	SpecPath string `mapstructure:"spec_path"`

	// DocJSONPath path for the doc.json generated by Swag (defaults to embedded)
	// If empty, use swag generated docs.SwaggerInfo
	DocJSONPath string `mapstructure:"doc_json_path"`

	// Whether deep linking is enabled (default true)
	DeepLinking bool `mapstructure:"deep_linking"`

	// Whether to persist authorization information (default true)
	PersistAuthorization bool `mapstructure:"persist_authorization"`

	// ValidatorURL validator URL (empty string disables validation)
	ValidatorURL string `mapstructure:"validator_url"`

	// OAuth2RedirectURL OAuth 2.0 redirect URL
	OAuth2RedirectURL string `mapstructure:"oauth2_redirect_url"`
}

// Returns default configuration
func DefaultConfig() Config {
	return Config{
		Enabled:              false,
		UIPath:               "/swagger/*any",
		SpecPath:             "/openapi.json",
		DocJSONPath:          "",
		DeepLinking:          true,
		PersistAuthorization: true,
		ValidatorURL:         "",
		OAuth2RedirectURL:    "",
	}
}

// Apply defaults
func (c *Config) ApplyDefaults() {
	if c.UIPath == "" {
		c.UIPath = "/swagger/*any"
	}
	if c.SpecPath == "" {
		c.SpecPath = "/openapi.json"
	}
}

// Validate configuration
func (c *Config) Validate() error {
	return nil
}

// SwaggerInfo API metadata
// Corresponds to swag's @title, @version annotations etc.
type SwaggerInfo struct {
	// Title API title (corresponds to @title)
	Title string `mapstructure:"title"`

	// Description API description (corresponding to @description)
	Description string `mapstructure:"description"`

	// Version API version (corresponds to @version)
	Version string `mapstructure:"version"`

	// Host host address (corresponds to @host)
	// Leave blank for automatic detection
	Host string `mapstructure:"host"`

	// BasePath API base path (corresponds to @BasePath)
	BasePath string `mapstructure:"base_path"`

	// Schemes supported protocols (corresponding to @schemes)
	// For example: ["http", "https"]
	Schemes []string `mapstructure:"schemes"`

	// Contact information
	Contact *ContactInfo `mapstructure:"contact"`

	// License information
	License *LicenseInfo `mapstructure:"license"`

	// Security Definitions
	SecurityDefinitions map[string]*SecurityDefinition `mapstructure:"security_definitions"`
}

// ContactInfo Contact information
type ContactInfo struct {
	Name  string `mapstructure:"name"`
	URL   string `mapstructure:"url"`
	Email string `mapstructure:"email"`
}

// LicenseInfo license information
type LicenseInfo struct {
	Name string `mapstructure:"name"`
	URL  string `mapstructure:"url"`
}

// SecurityDefinition Security definition
type SecurityDefinition struct {
	Type             string            `mapstructure:"type"`              // "apiKey", "oauth2", "basic"
	Description      string            `mapstructure:"description"`
	Name             string            `mapstructure:"name"`              // Header/Query Parameter Names
	In               string            `mapstructure:"in"`                // "header", "query"
	Flow             string            `mapstructure:"flow"`              // OAuth2 flow
	AuthorizationURL string            `mapstructure:"authorization_url"`
	TokenURL         string            `mapstructure:"token_url"`
	Scopes           map[string]string `mapstructure:"scopes"`
}

// DefaultSwaggerInfo returns the default API documentation metadata
func DefaultSwaggerInfo() SwaggerInfo {
	return SwaggerInfo{
		Title:       "API Documentation",
		Description: "API Documentation generated by Yogan Framework",
		Version:     "1.0.0",
		BasePath:    "/api",
		Schemes:     []string{"http", "https"},
	}
}

// BuildTime records the generation time of swag (for debugging)
var BuildTime = time.Now().Format(time.RFC3339)
