// Package swagger 提供 Swagger/OpenAPI 文档生成和展示能力
// 基于 swaggo/swag 实现注释驱动的文档生成
package swagger

import "time"

// Config Swagger 配置
type Config struct {
	// Enabled 是否启用 Swagger（默认 false）
	Enabled bool `mapstructure:"enabled"`

	// UIPath Swagger UI 路由路径（默认 "/swagger/*any"）
	UIPath string `mapstructure:"ui_path"`

	// SpecPath OpenAPI Spec 路由路径（默认 "/openapi.json"）
	SpecPath string `mapstructure:"spec_path"`

	// DocJSONPath swag 生成的 doc.json 路径（默认使用内嵌）
	// 如果为空，使用 swag 生成的 docs.SwaggerInfo
	DocJSONPath string `mapstructure:"doc_json_path"`

	// DeepLinking 是否启用深度链接（默认 true）
	DeepLinking bool `mapstructure:"deep_linking"`

	// PersistAuthorization 是否持久化认证信息（默认 true）
	PersistAuthorization bool `mapstructure:"persist_authorization"`

	// ValidatorURL 校验器 URL（空字符串禁用校验）
	ValidatorURL string `mapstructure:"validator_url"`

	// OAuth2RedirectURL OAuth2 重定向 URL
	OAuth2RedirectURL string `mapstructure:"oauth2_redirect_url"`
}

// DefaultConfig 返回默认配置
func DefaultConfig() Config {
	return Config{
		Enabled:              false,
		UIPath:               "/swagger/*any",
		SpecPath:             "/openapi.json",
		DocJSONPath:          "",
		DeepLinking:          true,
		PersistAuthorization: true,
		ValidatorURL:         "",
		OAuth2RedirectURL:    "",
	}
}

// ApplyDefaults 应用默认值
func (c *Config) ApplyDefaults() {
	if c.UIPath == "" {
		c.UIPath = "/swagger/*any"
	}
	if c.SpecPath == "" {
		c.SpecPath = "/openapi.json"
	}
}

// Validate 验证配置
func (c *Config) Validate() error {
	return nil
}

// SwaggerInfo API 文档元信息
// 对应 swag 的 @title, @version 等注释
type SwaggerInfo struct {
	// Title API 标题（对应 @title）
	Title string `mapstructure:"title"`

	// Description API 描述（对应 @description）
	Description string `mapstructure:"description"`

	// Version API 版本（对应 @version）
	Version string `mapstructure:"version"`

	// Host 主机地址（对应 @host）
	// 留空则自动检测
	Host string `mapstructure:"host"`

	// BasePath API 基础路径（对应 @BasePath）
	BasePath string `mapstructure:"base_path"`

	// Schemes 支持的协议（对应 @schemes）
	// 例如: ["http", "https"]
	Schemes []string `mapstructure:"schemes"`

	// Contact 联系人信息
	Contact *ContactInfo `mapstructure:"contact"`

	// License 许可证信息
	License *LicenseInfo `mapstructure:"license"`

	// SecurityDefinitions 安全定义
	SecurityDefinitions map[string]*SecurityDefinition `mapstructure:"security_definitions"`
}

// ContactInfo 联系人信息
type ContactInfo struct {
	Name  string `mapstructure:"name"`
	URL   string `mapstructure:"url"`
	Email string `mapstructure:"email"`
}

// LicenseInfo 许可证信息
type LicenseInfo struct {
	Name string `mapstructure:"name"`
	URL  string `mapstructure:"url"`
}

// SecurityDefinition 安全定义
type SecurityDefinition struct {
	Type             string            `mapstructure:"type"`              // "apiKey", "oauth2", "basic"
	Description      string            `mapstructure:"description"`
	Name             string            `mapstructure:"name"`              // Header/Query 参数名
	In               string            `mapstructure:"in"`                // "header", "query"
	Flow             string            `mapstructure:"flow"`              // OAuth2 flow
	AuthorizationURL string            `mapstructure:"authorization_url"`
	TokenURL         string            `mapstructure:"token_url"`
	Scopes           map[string]string `mapstructure:"scopes"`
}

// DefaultSwaggerInfo 返回默认的 API 文档元信息
func DefaultSwaggerInfo() SwaggerInfo {
	return SwaggerInfo{
		Title:       "API Documentation",
		Description: "API Documentation generated by Yogan Framework",
		Version:     "1.0.0",
		BasePath:    "/api",
		Schemes:     []string{"http", "https"},
	}
}

// BuildTime 记录 swag 生成时间（用于调试）
var BuildTime = time.Now().Format(time.RFC3339)
