package swagger

import (
	"github.com/gin-gonic/gin"
	"github.com/samber/do/v2"
)

// Setup quick method: Obtain Manager from DI container and register routes
// The application layer can call this method in the OnReady callback
//
// Using examples:
//
// import _ "your-app/docs" // import the docs package generated by swag init
//
//	func (a *App) onReady(core *application.Application) error {
//	    swagger.Setup(core.GetInjector(), core.GetHTTPServer().GetEngine())
//	    return nil
//	}
func Setup(injector do.Injector, engine *gin.Engine) error {
	mgr, err := do.Invoke[*Manager](injector)
	if err != nil {
		return err
	}
	if mgr == nil {
		return nil // Swagger is not enabled
	}

	mgr.RegisterRoutes(engine)
	return nil
}

// SetupWithInfo shortcut method: Set up SwaggerInfo and register routes
// For scenarios requiring dynamic setting of API information
//
// Usage example:
//
//	import (
//	    _ "your-app/docs"
//	    "your-app/docs"
//	)
//
//	func (a *App) onReady(core *application.Application) error {
// // Dynamically set API information
//	    docs.SwaggerInfo.Title = a.GetConfig().App.Name + " API"
//	    docs.SwaggerInfo.Version = a.GetVersion()
//	    docs.SwaggerInfo.Host = a.GetConfig().ApiServer.Host
//	    docs.SwaggerInfo.BasePath = "/api/v1"
//
//	    swagger.SetupWithInfo(core.GetInjector(), core.GetHTTPServer().GetEngine())
//	    return nil
//	}
func SetupWithInfo(injector do.Injector, engine *gin.Engine) error {
	mgr, err := do.Invoke[*Manager](injector)
	if err != nil {
		return err
	}
	if mgr == nil {
		return nil
	}

	mgr.SetupInfo()
	mgr.RegisterRoutes(engine)
	return nil
}

// MustSetup shortcut method: Set up Swagger (panic on failure)
func MustSetup(injector do.Injector, engine *gin.Engine) {
	if err := Setup(injector, engine); err != nil {
		panic(err)
	}
}
