package swagger

import (
	"net/http"

	"github.com/KOMKZ/go-yogan-framework/logger"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/swag"
	"go.uber.org/zap"
)

// Manager Swagger Manager
// Encapsulate swaggo initialization and Gin middleware mounting
type Manager struct {
	config Config
	info   SwaggerInfo
	logger *logger.CtxZapLogger
}

// Create Swagger Manager
func NewManager(cfg Config, info SwaggerInfo, log *logger.CtxZapLogger) *Manager {
	cfg.ApplyDefaults()
	return &Manager{
		config: cfg,
		info:   info,
		logger: log,
	}
}

// Returns whether Swagger is enabled
func (m *Manager) IsEnabled() bool {
	return m.config.Enabled
}

// GetConfig returns configuration
func (m *Manager) GetConfig() Config {
	return m.config
}

// GetInfo returns API documentation metadata
func (m *Manager) GetInfo() SwaggerInfo {
	return m.info
}

// SetupInfo sets up swag.SwaggerInfo (call before route registration)
// This method synchronizes the configured metadata to the swag global variable
func (m *Manager) SetupInfo() {
	if swag.GetSwagger("swagger") == nil {
		m.logger.Warn("swag.SwaggerInfo not initialized, please run 'swag init' first")
		return
	}

	// Get instance through swag.ReadDoc cannot be modified; application layer needs to import the docs package and set it up
	// Here only log prompt
	m.logger.Debug("Swagger info setup complete",
		zap.String("title", m.info.Title),
		zap.String("version", m.info.Version),
		zap.String("basePath", m.info.BasePath))
}

// RegisterRoutes registers Swagger routes to the Gin Engine
// This method is called by the application layer to mount Swagger UI and Spec routes
//
// Usage example:
//
// import _ "your-app/docs" // import the docs package generated by swag init
//	swaggerManager.RegisterRoutes(engine)
func (m *Manager) RegisterRoutes(engine *gin.Engine) {
	if !m.config.Enabled {
		m.logger.Debug("Swagger is disabled, skipping route registration")
		return
	}

	// Build ginSwagger configuration options
	opts := m.buildGinSwaggerOptions()

	// Register Swagger UI route
	engine.GET(m.config.UIPath, ginSwagger.WrapHandler(swaggerFiles.Handler, opts...))

	// Register OpenAPI Spec route (returns JSON)
	if m.config.SpecPath != "" {
		engine.GET(m.config.SpecPath, m.serveSpec)
	}

	m.logger.Info("Swagger routes registered",
		zap.String("ui_path", m.config.UIPath),
		zap.String("spec_path", m.config.SpecPath))
}

// buildGinSwaggerOptions build ginSwagger configuration options
func (m *Manager) buildGinSwaggerOptions() []func(*ginSwagger.Config) {
	opts := []func(*ginSwagger.Config){
		ginSwagger.DeepLinking(m.config.DeepLinking),
		ginSwagger.PersistAuthorization(m.config.PersistAuthorization),
	}

	if m.config.ValidatorURL != "" {
		opts = append(opts, ginSwagger.DocExpansion("none"))
	}

	if m.config.OAuth2RedirectURL != "" {
		opts = append(opts, ginSwagger.Oauth2DefaultClientID(""))
	}

	return opts
}

// serveSpec returns the OpenAPI Spec JSON
func (m *Manager) serveSpec(c *gin.Context) {
	doc, err := swag.ReadDoc("swagger")
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": ErrSwaggerDocNotFound.Wrap(err).Error(),
		})
		return
	}

	c.Header("Content-Type", "application/json")
	c.String(http.StatusOK, doc)
}

// Shutdown shutdown manager (implements do.Shutdownable)
func (m *Manager) Shutdown() error {
	m.logger.Debug("Swagger manager shutdown")
	return nil
}
